### ISSUE TITLE
Ридми

### ISSUE THREAD

**Issue by netypoj** [IvanKaziev/ArcheoGame#2]
Очень много лишнего и не нужного находится в ридми, читая его создается ощущение, что это какая-то 3д ммо рпг с кучей возможностей, а на деле.. Респект за использование json(а), правда в коде очень много ифоф, которые можно реализовать подругому.

**Comment by omixyy** [comment]
Если честно, я нашёл только один if, который можно более компактно оформить. Остальные просто используются для обхода ошибки KeyError в основном. 
А Readme, мне кажется, вполне хорошо оформлен. Там просто описан каждый персонаж, который есть в игре. Думаю, это не плохо. А каким бы тебе хотелось видеть Readme? Хотелось бы знать, какие недостатки ты видишь в том, что есть сейчас
